<?php

include_once('thacker_event.features.inc');

function thacker_event_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0] = array(
      'info' => t('New Event'), 
      'weight' => 0, 
      'status' => 0, 
    );
    return $blocks;
  }
  else if ($op == 'view') {
    switch ($delta) {
    case 0:
      // Your module will need to define this function to render the block.
      $block = array(
        'subject' => '', 
        'content' => l(t('Create a new event'), 'node/add/dt-event'),
      );
      return $block;
    }
  }
}
